#!/bin/sh
# Convert video to H264/ACC format
ffmpeg -i "$1" -init_hw_device qsv=hw -filter_hw_device hw -vf hwupload=extra_hw_frames=64,format=qsv -c:v h264_qsv -maxrate 5M -movflags +faststart -q:v 25 -c:a aac -q:a 2 "$2"