#!/bin/bash
# Convert video to H265 format
ffmpeg -i "$1" -init_hw_device qsv=hw -filter_hw_device hw -vf hwupload=extra_hw_frames=64,format=qsv -c:v hevc_qsv -maxrate 5M -movflags +faststart  -q 25 "$2"